- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--webhook-bind-address=::"
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--health-addr=[::]:9445"
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--profiler-address=[::]:8073"

