- op: replace
  path: /spec/template/spec/containers/0/args/0
  value: --metrics-addr=localhost:8083
- op: replace
  path: /spec/template/spec/containers/1/args/1
  value: --upstream=http://localhost:8083
